### ISSUE TITLE
Network mode awsvpc (fargate) conflicts with hostname

### ISSUE THREAD

**Issue by robmoorman** [labd/ecs-deplojo#26]
Fargate services requires network mode to be awsvpc. This conflicts with the hostname that is set by deplojo (were hostname is not allowed for awsvpc modes).

This results in an error while deploying the services:
```botocore.errorfactory.ClientException: An error occurred (ClientException) when calling the RegisterTaskDefinition operation: hostname is not supported on container when networkMode=awsvpc.```

If we apply a check on network mode, that would do the trick.

https://github.com/labd/ecs-deplojo/blob/fb7b153f84916c751c9e699a643b41f63af773eb/src/ecs_deplojo/task_definitions.py#L222-L229

**Comment by mikedingjan** [comment]
This issue is fixed in version 0.9.2, released to pypi as well: https://pypi.org/project/ecs-deplojo/
